import type { Metadata } from "next";
import { Outfit, Playfair_Display } from "next/font/google";

import "./globals.css";
import { Header } from "@/components/layout/header";
import Socials from "@/components/common/socials";

const playfair = Playfair_Display({
  variable: "--font-playfair-serif",
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.variable} ${playfair.variable}  antialiased relative h-full`}
      >
        <Header />
        {children}
        {/* <Socials /> */}
      </body>
    </html>
  );
}
