import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./../styles/globals.css";

const outfit = Outfit({
  variable: "--font-outfit-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en" suppressHydrationWarning>
      <body className={`${outfit.variable} } antialiased`}>{children}</body>
    </html>
  );
}
